### ISSUE TITLE
Clarify a license

### ISSUE THREAD

**Issue by blaind** [qnighy/libwebp-sys2-rs#6]
Hi! According to Cargo.toml, the repository uses BSD-3 as license (https://github.com/qnighy/libwebp-sys2-rs/blob/master/Cargo.toml#L15), could this be clarified as a separate LICENSE file as well?

**Comment by qnighy** [comment]
Done https://github.com/qnighy/libwebp-sys2-rs/commit/c03122de372e9ef041ebc072358fc5dd3edb701a
