### ISSUE TITLE
License file not include in the crate source

### ISSUE THREAD

**Issue by remilauzier** [qnighy/libwebp-sys2-rs#8]
Hi.
Fedora would prefer to have the license file include in the crate source instead of havind to download it as a separate file.
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by qnighy** [comment]
I released a version 0.1.3 including this change: https://github.com/qnighy/libwebp-sys2-rs/commit/c03122de372e9ef041ebc072358fc5dd3edb701a

Is this sufficient?

**Comment by remilauzier** [comment]
Yes. thanks!
